//import { Geist, Geist_Mono } from "next/font/google";
import { Sniglet } from 'next/font/google'
import "./globals.css";

const sniglet = Sniglet({
  variable: "--font-sniglet",
  subsets: ["latin"],
  weight: ['400']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sniglet.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
